export default () => [
    {
        id : "1",
        name: "Paracetamol",
        containerAmount: 25,
        containerUnit: "Comprimidos",
        expirationDate: "10 de dezembro",
        initialDate: "19 de julho",
        initialHour: "19:15",
        frequency: "4h em 4h",
        durationOfTreatmentType: "Semanas",
        durationOfTreatmentNum: 1,
        dosageQuantity: 1,
        dosageUnit: "Comprimidos",
        instructions: "Tomar em jejum",
        obs: "Esse medicamento é contra-indic."
    },
    {
        id : "2",
        name: "Pantoprazol",
        containerAmount: 20,
        containerUnit: "Unidades",
        expirationDate: "10 de dezembro",
        initialDate: "19 de julho",
        initialHour: "15:15",
        frequency: "6h em 6h",
        durationOfTreatmentType: "Semanas",
        durationOfTreatmentNum: 1,
        dosageQuantity: 5,
        dosageUnit: "Comprimidos",
        instructions: "Após o almoço",
        obs: "Se tomar vc morre."
    },
    {
        id : "3",
        name: "xczxzc",
        containerAmount: 20,
        containerUnit: "Unidades",
        expirationDate: "10 de dezembro",
        initialDate: "19 de julho",
        initialHour: "15:15",
        frequency: "6h em 6h",
        durationOfTreatmentType: "Semanas",
        durationOfTreatmentNum: 1,
        dosageQuantity: 5,
        dosageUnit: "Comprimidos",
        instructions: "Após o almoço",
        obs: "dsfsdfdfsdfsdfskdsfkdfkfdkfdksdkmk"
    },
]